### ISSUE TITLE
Can you lower compilers requirements to match golang releases

### ISSUE THREAD

**Issue by nlacey** [pijng/prep#3]
If you create a project, the go.mod file automatically is set to your current compiler.

If you want to match golang's currently supported compilers.  1.22 and 1.23

You could lower the go version within the go.mod file to 1.22  (assuming you aren't using any 1.23 features)

**Comment by pijng** [comment]
Hey @nlacey,

lowered the go version to 1.22.0

**Comment by nlacey** [comment]
thanks!  have a good week
